pipeline {
    agent any
    parameters {
        string(name: 'Project', defaultValue: 'Demo Project', description: 'Project to Deploy')
        choice(name: 'Environment', choices: ['QA', 'Staging'], description: 'Select Workspace Environment')
        string(name: 'Branch', defaultValue: 'master', description: 'Enter Branch Name to Run')
    }
    stages {
        stage('CleanWorkspace'){
           steps {
              cleanWs()
              sh 'whoami'
           }
        }
        stage('Terraform Code Pull'){
           steps {
              git branch: '${Branch}', url: 'https://github.com/praveen-edulakanti/Terraform-ALB-Application-Jenkins-Ansible.git'
           }
        }
        stage('Terraform Initialize'){
           steps {
              sh 'terraform init -var-file="${Environment}.tfvars"'
           }
        }
        stage('Select Workspace'){ 
           steps {
              sh 'terraform workspace new ${Environment} || terraform workspace select ${Environment}'
            }   
                
        }    
        stage('Terraform Plan'){ 
           steps {
              sh 'terraform plan -var-file="./env/${Environment}.tfvars" -out=${Environment}tfplanout'
              script {
              timeout(time: 10, unit: 'MINUTES') {
                input(id: "Terraform Apply Gate", message: "Terraform Plan ${params.Environment}tfplanout?", ok: 'Apply')
              }
            }
		   }
        }
        stage('Terraform Apply') { 
            steps {
             sh 'terraform apply -auto-approve "${Environment}"tfplanout'
            }    
        }
        stage('Application Deployment') {
            steps {
                //sh 'ansible all -m ping -i hosts'
                sh 'ansible-playbook -i hosts app-deploy.yml'
             }
        }
    }    
}
